appname="LibChecker"
appver="1"
appcode="1"
packagename="com.libchecker.kulipa"
theme="Theme_Material_Light_NoActionBar"
welcome_time="0"
debugmode=true
enableExtendedOutputSupport=false
enableDialogLog=false
user_permission={
  "QUERY_ALL_PACKAGES",
}
