{ LinearLayout;
  backgroundColor=backgroundc;
  orientation="vertical";
  gravity="center",
  layout_height="fill";
  layout_width="fill";
  {FrameLayout,
    layout_width="fill",
    layout_height="fill",
    {LinearLayout,
      id="yskempty",
      Visibility=8,
      layout_height="fill";
      layout_width="fill";
      orientation="vertical";
      {ImageView,
        layout_width="fill",
        layout_marginTop="88dp",
        layout_height="137dp",
        --scaleType="centerCrop",
        layout_gravity="center",
        imageDrawable=loadsvg("empty",cc.c.grey,true),
      },
      {TextView,
        layout_marginTop="8dp",
        layout_gravity="center",
        textSize="24sp",
        textColor=cc.c.on_background,
        text="空列表",
      },
    },
    {LinearLayout,

      orientation="vertical";
      layout_height="fill";
      layout_width="fill";
      {LinearLayout,
        id="extract",
        Visibility=8,
        layout_width="fill",
        layout_height="56dp",
        backgroundColor=cc.c.blue,
        {ImageView,
          layout_gravity="center",
          layout_marginLeft="16dp",
          imageDrawable=loadsvg("info",cc.c.on_background,true),
        },
        {TextView,
          layout_gravity="center",
          layout_marginLeft="8dp",
          textColor=cc.c.on_background,
          text="该应用声明了\nandroid:extractNativeLibs=\"false\"",
        },
      },
      {RecyclerView,
        id="yskrec",
        layout_width="fill",
        layout_height="fill",
        --BackgroundColor=backgroundc,
      }
    }
  }
}